// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260818.1

#pragma once
#ifndef WINRT_AccountVault_1_H
#define WINRT_AccountVault_1_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/AccountVault.0.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::AccountVault
{
    struct WINRT_IMPL_EMPTY_BASES IMainWindow :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMainWindow>
    {
        IMainWindow(std::nullptr_t = nullptr) noexcept {}
        IMainWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMainWindowFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMainWindowFactory>
    {
        IMainWindowFactory(std::nullptr_t = nullptr) noexcept {}
        IMainWindowFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
