// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260818.1

#pragma once
#ifndef WINRT_AccountVault_2_H
#define WINRT_AccountVault_2_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/Microsoft.UI.Xaml.1.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.1.h"
#include "winrt/impl/AccountVault.1.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::AccountVault
{
    struct WINRT_IMPL_EMPTY_BASES MainWindow : winrt::AccountVault::IMainWindow,
        impl::base<MainWindow, winrt::Microsoft::UI::Xaml::Window>,
        impl::require<MainWindow, winrt::Microsoft::UI::Xaml::IWindow, winrt::Microsoft::UI::Xaml::IWindow2>
    {
        MainWindow(std::nullptr_t) noexcept {}
        MainWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::AccountVault::IMainWindow(ptr, take_ownership_from_abi) {}
        MainWindow();
    };
    struct WINRT_IMPL_EMPTY_BASES XamlMetaDataProvider : winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider
    {
        XamlMetaDataProvider(std::nullptr_t) noexcept {}
        XamlMetaDataProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider(ptr, take_ownership_from_abi) {}
        XamlMetaDataProvider();
    };
}
#endif
