// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260818.1

#pragma once
#ifndef WINRT_AccountVault_0_H
#define WINRT_AccountVault_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::AccountVault
{
    struct IMainWindow;
    struct IMainWindowFactory;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
WINRT_EXPORT namespace winrt::impl
{
    template <> struct category<winrt::AccountVault::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::AccountVault::IMainWindowFactory>{ using type = interface_category; };
    template <> struct category<winrt::AccountVault::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::AccountVault::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::AccountVault::MainWindow> = L"AccountVault.MainWindow";
    template <> inline constexpr auto& name_v<winrt::AccountVault::XamlMetaDataProvider> = L"AccountVault.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::AccountVault::IMainWindow> = L"AccountVault.IMainWindow";
    template <> inline constexpr auto& name_v<winrt::AccountVault::IMainWindowFactory> = L"AccountVault.IMainWindowFactory";
    template <> inline constexpr guid guid_v<winrt::AccountVault::IMainWindow>{ 0x73A24087,0xC4C4,0x5836,{ 0xB4,0x5B,0x6E,0x07,0x40,0x68,0x40,0x0E } }; // 73A24087-C4C4-5836-B45B-6E074068400E
    template <> inline constexpr guid guid_v<winrt::AccountVault::IMainWindowFactory>{ 0xC9DF4291,0x24FC,0x571A,{ 0xAD,0x90,0x3D,0xA8,0x8F,0xAA,0x68,0x54 } }; // C9DF4291-24FC-571A-AD90-3DA88FAA6854
    template <> struct default_interface<winrt::AccountVault::MainWindow>{ using type = winrt::AccountVault::IMainWindow; };
    template <> struct default_interface<winrt::AccountVault::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::AccountVault::IMainWindow>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::AccountVault::IMainWindowFactory>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall CreateInstance(void*, void**, void**) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_AccountVault_IMainWindow
    {
    };
    template <> struct consume<winrt::AccountVault::IMainWindow>
    {
        template <typename D> using type = consume_AccountVault_IMainWindow<D>;
    };
    template <typename D>
    struct consume_AccountVault_IMainWindowFactory
    {
        auto CreateInstance(winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const;
    };
    template <> struct consume<winrt::AccountVault::IMainWindowFactory>
    {
        template <typename D> using type = consume_AccountVault_IMainWindowFactory<D>;
    };
}
#endif
