
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "MainWindow.xaml.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

namespace winrt::AccountVault::implementation
{


    using Application = ::winrt::Microsoft::UI::Xaml::Application;
    using ComponentResourceLocation = ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ComponentResourceLocation;
    using DataTemplate = ::winrt::Microsoft::UI::Xaml::DataTemplate;
    using DependencyObject = ::winrt::Microsoft::UI::Xaml::DependencyObject;
    using DependencyProperty = ::winrt::Microsoft::UI::Xaml::DependencyProperty;
    using IComponentConnector = ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector;
    using Uri = ::winrt::Windows::Foundation::Uri;
    using XamlBindingHelper = ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper;

    template <typename D, typename ... I>
    void MainWindowT<D, I...>::InitializeComponent()
    {
        if (!_contentLoaded)
        {
            _contentLoaded = true;
            ::winrt::Windows::Foundation::Uri resourceLocator{ L"ms-appx:///MainWindow.xaml" };
            ::winrt::Microsoft::UI::Xaml::Application::LoadComponent(*this, resourceLocator, ComponentResourceLocation::Application);
        }
    }

    template <typename D, typename ... I>
    void MainWindowT<D, I...>::Connect(int32_t connectionId, IInspectable const& target)
    {
        switch (connectionId)
        {
        case 2:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Grid>();
                this->AdaptiveHost(targetElement);
            }
            break;
        case 32:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::VisualStateGroup>();
                this->WindowWidthStates(targetElement);
            }
            break;
        case 33:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::VisualState>();
                this->WideShell(targetElement);
            }
            break;
        case 34:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::VisualState>();
                this->CenterOnlyShell(targetElement);
            }
            break;
        case 35:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::VisualState>();
                this->CompactShell(targetElement);
            }
            break;
        case 36:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::StateTrigger>();
                this->CompactShellTrigger(targetElement);
            }
            break;
        case 37:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::StateTrigger>();
                this->CenterOnlyShellTrigger(targetElement);
            }
            break;
        case 38:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::StateTrigger>();
                this->WideShellTrigger(targetElement);
            }
            break;
        case 39:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Border>();
                this->ShellFrame(targetElement);
            }
            break;
        case 40:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Grid>();
                this->RootGrid(targetElement);
            }
            break;
        case 41:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition>();
                this->LeftRailColumn(targetElement);
            }
            break;
        case 42:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition>();
                this->RightRailColumn(targetElement);
            }
            break;
        case 43:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Border>();
                this->LeftRail(targetElement);
            }
            break;
        case 44:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::NavigationView>();
                this->CompactNavigation(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.SelectionChanged([weakThis](::winrt::Microsoft::UI::Xaml::Controls::NavigationView const& p0, ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewSelectionChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->WorkspaceNavigation_SelectionChanged(p0, p1);
                    }
                });
            }
            break;
        case 45:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Border>();
                this->StatusContainer(targetElement);
            }
            break;
        case 46:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Border>();
                this->RightRail(targetElement);
            }
            break;
        case 47:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Border>();
                this->LockOverlay(targetElement);
            }
            break;
        case 48:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Button>();
                this->UnlockButton(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->UnlockButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 49:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->RightRailHeader(targetElement);
            }
            break;
        case 50:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBox>();
                this->ThemePicker(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.SelectionChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::SelectionChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ThemePicker_SelectionChanged(p0, p1);
                    }
                });
            }
            break;
        case 51:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Button>();
                this->CustomizeColorsButton(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->CustomizeColorsButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 52:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Button>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->PasswordGeneratorButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 53:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBoxItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.RightTapped([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Input::RightTappedRoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ThemeOption_RightTapped(p0, p1);
                    }
                });
            }
            break;
        case 54:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBoxItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.RightTapped([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Input::RightTappedRoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ThemeOption_RightTapped(p0, p1);
                    }
                });
            }
            break;
        case 55:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBoxItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.RightTapped([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Input::RightTappedRoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ThemeOption_RightTapped(p0, p1);
                    }
                });
            }
            break;
        case 56:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBoxItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.RightTapped([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Input::RightTappedRoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ThemeOption_RightTapped(p0, p1);
                    }
                });
            }
            break;
        case 57:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBoxItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.RightTapped([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Input::RightTappedRoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ThemeOption_RightTapped(p0, p1);
                    }
                });
            }
            break;
        case 58:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBoxItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.RightTapped([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Input::RightTappedRoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ThemeOption_RightTapped(p0, p1);
                    }
                });
            }
            break;
        case 59:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBoxItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.RightTapped([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Input::RightTappedRoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ThemeOption_RightTapped(p0, p1);
                    }
                });
            }
            break;
        case 60:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBoxItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.RightTapped([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Input::RightTappedRoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ThemeOption_RightTapped(p0, p1);
                    }
                });
            }
            break;
        case 61:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBoxItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.RightTapped([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Input::RightTappedRoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ThemeOption_RightTapped(p0, p1);
                    }
                });
            }
            break;
        case 62:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBoxItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.RightTapped([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Input::RightTappedRoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ThemeOption_RightTapped(p0, p1);
                    }
                });
            }
            break;
        case 63:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Grid>();
                this->StatusGrid(targetElement);
            }
            break;
        case 64:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition>();
                this->StatusSizeColumn(targetElement);
            }
            break;
        case 65:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition>();
                this->StatusDividerColumn(targetElement);
            }
            break;
        case 66:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition>();
                this->StatusTimerColumn(targetElement);
            }
            break;
        case 67:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->StatusText(targetElement);
            }
            break;
        case 68:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->WindowSizeText(targetElement);
            }
            break;
        case 69:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->StatusDividerText(targetElement);
            }
            break;
        case 70:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->AutoLockStatusText(targetElement);
            }
            break;
        case 71:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem>();
                this->LauncherNavigationItem(targetElement);
            }
            break;
        case 72:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem>();
                this->CredentialNavigationItem(targetElement);
            }
            break;
        case 73:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Border>();
                this->AccountWorkspace(targetElement);
            }
            break;
        case 74:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Grid>();
                this->HeaderGrid(targetElement);
            }
            break;
        case 75:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Grid>();
                this->ToolbarGrid(targetElement);
            }
            break;
        case 76:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ListView>();
                this->AccountsList(targetElement);
            }
            break;
        case 77:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::StackPanel>();
                this->EmptyState(targetElement);
            }
            break;
        case 78:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->EmptyStateTitle(targetElement);
            }
            break;
        case 79:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->EmptyStateSubtitle(targetElement);
            }
            break;
        case 80:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition>();
                this->ToolbarColumn0(targetElement);
            }
            break;
        case 81:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition>();
                this->ToolbarColumn1(targetElement);
            }
            break;
        case 82:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition>();
                this->ToolbarColumn2(targetElement);
            }
            break;
        case 83:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition>();
                this->ToolbarColumn3(targetElement);
            }
            break;
        case 84:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBox>();
                this->SearchBox(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.TextChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::TextChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->SearchBox_TextChanged(p0, p1);
                    }
                });
            }
            break;
        case 85:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::ComboBox>();
                this->RecordFilter(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.SelectionChanged([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::Controls::SelectionChangedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->RecordFilter_SelectionChanged(p0, p1);
                    }
                });
            }
            break;
        case 86:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Button>();
                this->TopAddAccountButton(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->AddAccountButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 87:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::DropDownButton>();
                this->TopMoreActionsButton(targetElement);
            }
            break;
        case 88:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                this->TopImportOneMenuItem(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ImportOneAccountButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 89:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                this->TopImportAllMenuItem(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ImportAllAccountsButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 90:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                this->TopExportAllMenuItem(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ExportAllAccountsButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 91:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::DropDownButton>();
                this->AccountActionsButton(targetElement);
            }
            break;
        case 92:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                this->CompactAddMenuItem(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->AddAccountButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 93:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                this->CompactImportOneMenuItem(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ImportOneAccountButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 94:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                this->CompactImportAllMenuItem(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ImportAllAccountsButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 95:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                this->CompactExportAllMenuItem(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->ExportAllAccountsButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 96:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->CustomizeColorsButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 97:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->PasswordGeneratorButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 98:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->CompactThemeMenuItem_Click(p0, p1);
                    }
                });
            }
            break;
        case 99:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->CompactThemeMenuItem_Click(p0, p1);
                    }
                });
            }
            break;
        case 100:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->CompactThemeMenuItem_Click(p0, p1);
                    }
                });
            }
            break;
        case 101:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->CompactThemeMenuItem_Click(p0, p1);
                    }
                });
            }
            break;
        case 102:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->CompactThemeMenuItem_Click(p0, p1);
                    }
                });
            }
            break;
        case 103:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->CompactThemeMenuItem_Click(p0, p1);
                    }
                });
            }
            break;
        case 104:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->CompactThemeMenuItem_Click(p0, p1);
                    }
                });
            }
            break;
        case 105:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->CompactThemeMenuItem_Click(p0, p1);
                    }
                });
            }
            break;
        case 106:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->CompactThemeMenuItem_Click(p0, p1);
                    }
                });
            }
            break;
        case 107:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem>();
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->CompactThemeMenuItem_Click(p0, p1);
                    }
                });
            }
            break;
        case 108:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->HeaderTitle(targetElement);
            }
            break;
        case 109:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                this->HeaderSubtitle(targetElement);
            }
            break;
        case 110:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton>();
                this->LauncherWorkspaceButton(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->LauncherWorkspaceButton_Click(p0, p1);
                    }
                });
            }
            break;
        case 111:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton>();
                this->CredentialWorkspaceButton(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.Click([weakThis](::winrt::Windows::Foundation::IInspectable const& p0, ::winrt::Microsoft::UI::Xaml::RoutedEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->CredentialWorkspaceButton_Click(p0, p1);
                    }
                });
            }
            break;
        }
        _contentLoaded = true;
    }

    template <typename D, typename ... I>
    void MainWindowT<D, I...>::DisconnectUnloadedObject(int32_t)
    {
        throw ::winrt::hresult_invalid_argument { L"No unloadable objects to disconnect." };
    }

    template <typename D, typename ... I>
    void MainWindowT<D, I...>::UnloadObject(DependencyObject const&)
    {
        throw ::winrt::hresult_invalid_argument { L"No unloadable objects." };
    }


    template <typename D, typename... I>
    IComponentConnector MainWindowT<D, I...>::GetBindingConnector(int32_t, IInspectable const&)
    {
        return nullptr;
    }

    template struct MainWindowT<struct MainWindow>;
}


#pragma warning(pop)


