
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Input.h>)
#include <winrt/Microsoft.UI.Xaml.Input.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif
#if __has_include(<winrt/Windows.Foundation.h>)
#include <winrt/Windows.Foundation.h>
#endif


namespace winrt::AccountVault::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainWindowT : public ::winrt::AccountVault::implementation::MainWindow_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename MainWindowT::base_type;
        using base_type::base_type;
        using class_type = typename MainWindowT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::Grid AdaptiveHost()
        {
            return _AdaptiveHost;
        }
        void AdaptiveHost(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _AdaptiveHost = value;
        }

        ::winrt::Microsoft::UI::Xaml::VisualStateGroup WindowWidthStates()
        {
            return _WindowWidthStates;
        }
        void WindowWidthStates(::winrt::Microsoft::UI::Xaml::VisualStateGroup value)
        {
            _WindowWidthStates = value;
        }

        ::winrt::Microsoft::UI::Xaml::VisualState WideShell()
        {
            return _WideShell;
        }
        void WideShell(::winrt::Microsoft::UI::Xaml::VisualState value)
        {
            _WideShell = value;
        }

        ::winrt::Microsoft::UI::Xaml::VisualState CenterOnlyShell()
        {
            return _CenterOnlyShell;
        }
        void CenterOnlyShell(::winrt::Microsoft::UI::Xaml::VisualState value)
        {
            _CenterOnlyShell = value;
        }

        ::winrt::Microsoft::UI::Xaml::VisualState CompactShell()
        {
            return _CompactShell;
        }
        void CompactShell(::winrt::Microsoft::UI::Xaml::VisualState value)
        {
            _CompactShell = value;
        }

        ::winrt::Microsoft::UI::Xaml::StateTrigger CompactShellTrigger()
        {
            return _CompactShellTrigger;
        }
        void CompactShellTrigger(::winrt::Microsoft::UI::Xaml::StateTrigger value)
        {
            _CompactShellTrigger = value;
        }

        ::winrt::Microsoft::UI::Xaml::StateTrigger CenterOnlyShellTrigger()
        {
            return _CenterOnlyShellTrigger;
        }
        void CenterOnlyShellTrigger(::winrt::Microsoft::UI::Xaml::StateTrigger value)
        {
            _CenterOnlyShellTrigger = value;
        }

        ::winrt::Microsoft::UI::Xaml::StateTrigger WideShellTrigger()
        {
            return _WideShellTrigger;
        }
        void WideShellTrigger(::winrt::Microsoft::UI::Xaml::StateTrigger value)
        {
            _WideShellTrigger = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border ShellFrame()
        {
            return _ShellFrame;
        }
        void ShellFrame(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _ShellFrame = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid RootGrid()
        {
            return _RootGrid;
        }
        void RootGrid(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _RootGrid = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition LeftRailColumn()
        {
            return _LeftRailColumn;
        }
        void LeftRailColumn(::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition value)
        {
            _LeftRailColumn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition RightRailColumn()
        {
            return _RightRailColumn;
        }
        void RightRailColumn(::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition value)
        {
            _RightRailColumn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border LeftRail()
        {
            return _LeftRail;
        }
        void LeftRail(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _LeftRail = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::NavigationView CompactNavigation()
        {
            return _CompactNavigation;
        }
        void CompactNavigation(::winrt::Microsoft::UI::Xaml::Controls::NavigationView value)
        {
            _CompactNavigation = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border StatusContainer()
        {
            return _StatusContainer;
        }
        void StatusContainer(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _StatusContainer = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border RightRail()
        {
            return _RightRail;
        }
        void RightRail(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _RightRail = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border LockOverlay()
        {
            return _LockOverlay;
        }
        void LockOverlay(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _LockOverlay = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button UnlockButton()
        {
            return _UnlockButton;
        }
        void UnlockButton(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _UnlockButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock RightRailHeader()
        {
            return _RightRailHeader;
        }
        void RightRailHeader(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _RightRailHeader = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox ThemePicker()
        {
            return _ThemePicker;
        }
        void ThemePicker(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _ThemePicker = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button CustomizeColorsButton()
        {
            return _CustomizeColorsButton;
        }
        void CustomizeColorsButton(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _CustomizeColorsButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid StatusGrid()
        {
            return _StatusGrid;
        }
        void StatusGrid(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _StatusGrid = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition StatusSizeColumn()
        {
            return _StatusSizeColumn;
        }
        void StatusSizeColumn(::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition value)
        {
            _StatusSizeColumn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition StatusDividerColumn()
        {
            return _StatusDividerColumn;
        }
        void StatusDividerColumn(::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition value)
        {
            _StatusDividerColumn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition StatusTimerColumn()
        {
            return _StatusTimerColumn;
        }
        void StatusTimerColumn(::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition value)
        {
            _StatusTimerColumn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock StatusText()
        {
            return _StatusText;
        }
        void StatusText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _StatusText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock WindowSizeText()
        {
            return _WindowSizeText;
        }
        void WindowSizeText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _WindowSizeText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock StatusDividerText()
        {
            return _StatusDividerText;
        }
        void StatusDividerText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _StatusDividerText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock AutoLockStatusText()
        {
            return _AutoLockStatusText;
        }
        void AutoLockStatusText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _AutoLockStatusText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem LauncherNavigationItem()
        {
            return _LauncherNavigationItem;
        }
        void LauncherNavigationItem(::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem value)
        {
            _LauncherNavigationItem = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem CredentialNavigationItem()
        {
            return _CredentialNavigationItem;
        }
        void CredentialNavigationItem(::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem value)
        {
            _CredentialNavigationItem = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border AccountWorkspace()
        {
            return _AccountWorkspace;
        }
        void AccountWorkspace(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _AccountWorkspace = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid HeaderGrid()
        {
            return _HeaderGrid;
        }
        void HeaderGrid(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _HeaderGrid = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid ToolbarGrid()
        {
            return _ToolbarGrid;
        }
        void ToolbarGrid(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _ToolbarGrid = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ListView AccountsList()
        {
            return _AccountsList;
        }
        void AccountsList(::winrt::Microsoft::UI::Xaml::Controls::ListView value)
        {
            _AccountsList = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::StackPanel EmptyState()
        {
            return _EmptyState;
        }
        void EmptyState(::winrt::Microsoft::UI::Xaml::Controls::StackPanel value)
        {
            _EmptyState = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock EmptyStateTitle()
        {
            return _EmptyStateTitle;
        }
        void EmptyStateTitle(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _EmptyStateTitle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock EmptyStateSubtitle()
        {
            return _EmptyStateSubtitle;
        }
        void EmptyStateSubtitle(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _EmptyStateSubtitle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition ToolbarColumn0()
        {
            return _ToolbarColumn0;
        }
        void ToolbarColumn0(::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition value)
        {
            _ToolbarColumn0 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition ToolbarColumn1()
        {
            return _ToolbarColumn1;
        }
        void ToolbarColumn1(::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition value)
        {
            _ToolbarColumn1 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition ToolbarColumn2()
        {
            return _ToolbarColumn2;
        }
        void ToolbarColumn2(::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition value)
        {
            _ToolbarColumn2 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition ToolbarColumn3()
        {
            return _ToolbarColumn3;
        }
        void ToolbarColumn3(::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition value)
        {
            _ToolbarColumn3 = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox SearchBox()
        {
            return _SearchBox;
        }
        void SearchBox(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _SearchBox = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox RecordFilter()
        {
            return _RecordFilter;
        }
        void RecordFilter(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _RecordFilter = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button TopAddAccountButton()
        {
            return _TopAddAccountButton;
        }
        void TopAddAccountButton(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _TopAddAccountButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::DropDownButton TopMoreActionsButton()
        {
            return _TopMoreActionsButton;
        }
        void TopMoreActionsButton(::winrt::Microsoft::UI::Xaml::Controls::DropDownButton value)
        {
            _TopMoreActionsButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem TopImportOneMenuItem()
        {
            return _TopImportOneMenuItem;
        }
        void TopImportOneMenuItem(::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem value)
        {
            _TopImportOneMenuItem = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem TopImportAllMenuItem()
        {
            return _TopImportAllMenuItem;
        }
        void TopImportAllMenuItem(::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem value)
        {
            _TopImportAllMenuItem = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem TopExportAllMenuItem()
        {
            return _TopExportAllMenuItem;
        }
        void TopExportAllMenuItem(::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem value)
        {
            _TopExportAllMenuItem = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::DropDownButton AccountActionsButton()
        {
            return _AccountActionsButton;
        }
        void AccountActionsButton(::winrt::Microsoft::UI::Xaml::Controls::DropDownButton value)
        {
            _AccountActionsButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem CompactAddMenuItem()
        {
            return _CompactAddMenuItem;
        }
        void CompactAddMenuItem(::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem value)
        {
            _CompactAddMenuItem = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem CompactImportOneMenuItem()
        {
            return _CompactImportOneMenuItem;
        }
        void CompactImportOneMenuItem(::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem value)
        {
            _CompactImportOneMenuItem = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem CompactImportAllMenuItem()
        {
            return _CompactImportAllMenuItem;
        }
        void CompactImportAllMenuItem(::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem value)
        {
            _CompactImportAllMenuItem = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem CompactExportAllMenuItem()
        {
            return _CompactExportAllMenuItem;
        }
        void CompactExportAllMenuItem(::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem value)
        {
            _CompactExportAllMenuItem = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock HeaderTitle()
        {
            return _HeaderTitle;
        }
        void HeaderTitle(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _HeaderTitle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock HeaderSubtitle()
        {
            return _HeaderSubtitle;
        }
        void HeaderSubtitle(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _HeaderSubtitle = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton LauncherWorkspaceButton()
        {
            return _LauncherWorkspaceButton;
        }
        void LauncherWorkspaceButton(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _LauncherWorkspaceButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton CredentialWorkspaceButton()
        {
            return _CredentialWorkspaceButton;
        }
        void CredentialWorkspaceButton(::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton value)
        {
            _CredentialWorkspaceButton = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct MainWindow_obj3_Bindings;
        struct MainWindow_obj17_Bindings;
        struct MainWindow_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::Grid _AdaptiveHost{nullptr};
        ::winrt::Microsoft::UI::Xaml::VisualStateGroup _WindowWidthStates{nullptr};
        ::winrt::Microsoft::UI::Xaml::VisualState _WideShell{nullptr};
        ::winrt::Microsoft::UI::Xaml::VisualState _CenterOnlyShell{nullptr};
        ::winrt::Microsoft::UI::Xaml::VisualState _CompactShell{nullptr};
        ::winrt::Microsoft::UI::Xaml::StateTrigger _CompactShellTrigger{nullptr};
        ::winrt::Microsoft::UI::Xaml::StateTrigger _CenterOnlyShellTrigger{nullptr};
        ::winrt::Microsoft::UI::Xaml::StateTrigger _WideShellTrigger{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _ShellFrame{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _RootGrid{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition _LeftRailColumn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition _RightRailColumn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _LeftRail{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::NavigationView _CompactNavigation{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _StatusContainer{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _RightRail{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _LockOverlay{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _UnlockButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _RightRailHeader{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _ThemePicker{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _CustomizeColorsButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _StatusGrid{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition _StatusSizeColumn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition _StatusDividerColumn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition _StatusTimerColumn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _StatusText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _WindowSizeText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _StatusDividerText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _AutoLockStatusText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem _LauncherNavigationItem{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem _CredentialNavigationItem{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _AccountWorkspace{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _HeaderGrid{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _ToolbarGrid{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ListView _AccountsList{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::StackPanel _EmptyState{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _EmptyStateTitle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _EmptyStateSubtitle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition _ToolbarColumn0{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition _ToolbarColumn1{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition _ToolbarColumn2{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ColumnDefinition _ToolbarColumn3{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _SearchBox{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _RecordFilter{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _TopAddAccountButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::DropDownButton _TopMoreActionsButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem _TopImportOneMenuItem{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem _TopImportAllMenuItem{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem _TopExportAllMenuItem{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::DropDownButton _AccountActionsButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem _CompactAddMenuItem{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem _CompactImportOneMenuItem{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem _CompactImportAllMenuItem{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItem _CompactExportAllMenuItem{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _HeaderTitle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _HeaderSubtitle{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _LauncherWorkspaceButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ToggleButton _CredentialWorkspaceButton{nullptr};
    };
}

