// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260818.1

#pragma once
#ifdef WINRT_IMPORT_MODULE
#include "winrt/base_macros.h"
import winrt.AccountVault;
import winrt.Microsoft.UI.Xaml;
#else // WINRT_IMPORT_MODULE
#include "winrt/AccountVault.h"
#include "winrt/Microsoft.UI.Xaml.h"
#endif // WINRT_IMPORT_MODULE
namespace winrt::AccountVault::implementation
{
    template <typename D, typename... I>
    struct WINRT_IMPL_EMPTY_BASES MainWindow_base : implements<D, AccountVault::MainWindow, composable, composing, I...>,
        impl::require<D, winrt::Microsoft::UI::Xaml::IWindow, winrt::Microsoft::UI::Xaml::IWindow2>,
        impl::base<D, winrt::Microsoft::UI::Xaml::Window>
    {
        using base_type = MainWindow_base;
        using class_type = AccountVault::MainWindow;
        using implements_type = typename MainWindow_base::implements_type;
        using implements_type::implements_type;
        using composable_base = winrt::Microsoft::UI::Xaml::Window;
        hstring GetRuntimeClassName() const override
        {
            return L"AccountVault.MainWindow";
        }
        MainWindow_base()
        {
            impl::call_factory<winrt::Microsoft::UI::Xaml::Window, winrt::Microsoft::UI::Xaml::IWindowFactory>([&](winrt::Microsoft::UI::Xaml::IWindowFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(*this, this->m_inner); });
        }
    };
}
namespace winrt::AccountVault::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES MainWindowT : implements<D, winrt::Windows::Foundation::IActivationFactory, winrt::AccountVault::IMainWindowFactory, I...>
    {
        using instance_type = AccountVault::MainWindow;

        hstring GetRuntimeClassName() const
        {
            return L"AccountVault.MainWindow";
        }
        auto CreateInstance(winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface)
        {
            return impl::composable_factory<T>::template CreateInstance<winrt::AccountVault::MainWindow>(baseInterface, innerInterface);
        }
        [[noreturn]] winrt::Windows::Foundation::IInspectable ActivateInstance() const
        {
            throw hresult_not_implemented();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_MAINWINDOW_XAML_G_H) || __has_include("MainWindow.xaml.g.h")

#include "MainWindow.xaml.g.h"

#else

namespace winrt::AccountVault::implementation
{
    template <typename D, typename... I>
    using MainWindowT = MainWindow_base<D, I...>;
}

#endif
