// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260818.1

void* winrt_make_AccountVault_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::AccountVault::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::AccountVault
{
    MainWindow::MainWindow() :
        MainWindow(make<AccountVault::implementation::MainWindow>())
    {
    }
}
