// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260818.1

void* winrt_make_AccountVault_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::AccountVault::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::AccountVault
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<AccountVault::implementation::XamlMetaDataProvider>())
    {
    }
}
