// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260818.1

#pragma once
#ifndef WINRT_AccountVault_H
#define WINRT_AccountVault_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260818.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260818.1"
#include "winrt/impl/Microsoft.UI.Xaml.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.2.h"
#include "winrt/impl/AccountVault.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_AccountVault_IMainWindowFactory<D>::CreateInstance(winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const
    {
        void* value{};
        consume_general<winrt::AccountVault::IMainWindowFactory, D>(static_cast<D const*>(this), &abi_t<winrt::AccountVault::IMainWindowFactory>::CreateInstance, *(void**)(&baseInterface), impl::bind_out(innerInterface), &value);
        return winrt::AccountVault::MainWindow{ value, take_ownership_from_abi };
    }
    template <typename D>
    struct produce<D, winrt::AccountVault::IMainWindow> : produce_base<D, winrt::AccountVault::IMainWindow>
    {
    };
    template <typename D>
    struct produce<D, winrt::AccountVault::IMainWindowFactory> : produce_base<D, winrt::AccountVault::IMainWindowFactory>
    {
        std::int32_t __stdcall CreateInstance(void* baseInterface, void** innerInterface, void** value) noexcept final try
        {
            if (innerInterface) *innerInterface = nullptr;
            winrt::Windows::Foundation::IInspectable winrt_impl_innerInterface;
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::AccountVault::MainWindow>(this->shim().CreateInstance(*reinterpret_cast<winrt::Windows::Foundation::IInspectable const*>(&baseInterface), winrt_impl_innerInterface));
            if (innerInterface) *innerInterface = detach_abi(winrt_impl_innerInterface);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::AccountVault
{
    template <typename D, typename... Interfaces>
    struct MainWindowT :
        implements<D, winrt::Windows::Foundation::IInspectable, composing, Interfaces...>,
        impl::require<D, winrt::AccountVault::IMainWindow, winrt::Microsoft::UI::Xaml::IWindow, winrt::Microsoft::UI::Xaml::IWindow2>,
        impl::base<D, MainWindow, winrt::Microsoft::UI::Xaml::Window>
    {
        using composable = MainWindow;
    protected:
        MainWindowT()
        {
            impl::call_factory<MainWindow, IMainWindowFactory>([&](IMainWindowFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(*this, this->m_inner); });
        }
    };
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::AccountVault::IMainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::AccountVault::IMainWindowFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::AccountVault::MainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::AccountVault::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
